### ISSUE TITLE
Cannot install library

### ISSUE THREAD

**Issue by aleksat90** [kevinpt/ripyl#2]
Hello Kevin,

I'm facing for almost three days issue installing this library on my computer. I'm using Python 3.6.2 Anaconda, Inc. Whey I try to install the missing packages, python says it is already installed. Do you know maybe how to solve this issue?

OS: Win10 64bit

`E:\03_Programiranje\dekoder\dekod\ripyl>python setup.py install
Extracting in C:\Users\naskomp\AppData\Local\Temp\tmp1nphe5p9
Traceback (most recent call last):

  File "E:\03_Programiranje\dekoder\dekod\ripyl\distribute_setup.py", line 150, in use_setuptools
    raise ImportError
ImportError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 5, in <module>
    distribute_setup.use_setuptools()
  File "E:\03_Programiranje\dekoder\dekod\ripyl\distribute_setup.py", line 152, in use_setuptools
    return _do_download(version, download_base, to_dir, download_delay)
  File "E:\03_Programiranje\dekoder\dekod\ripyl\distribute_setup.py", line 132, in _do_download
    _build_egg(egg, tarball, to_dir)
  File "E:\03_Programiranje\dekoder\dekod\ripyl\distribute_setup.py", line 105, in _build_egg
    _extractall(tar)
  File "E:\03_Programiranje\dekoder\dekod\ripyl\distribute_setup.py", line 500, in _extractall
    self.chown(tarinfo, dirpath)
TypeError: chown() missing 1 required positional argument: 'numeric_owner'`

**Comment by aleksat90** [comment]
Coudn't sort out why it wasn't working on Python 3.6, but it was all fine with Python 2.7. Therefore, this is my recommendation.
